---
- name: Create Key Pair
  amazon.aws.ec2_key:
    name: sockskey
    region: "{{ region }}"
    file_name: ./sockskey.pem
    aws_access_key: "{{ access_key }}"  # From vault as defined
    aws_secret_key: "{{ secret_key }}"
  register: socks_key_pair

- name: Print key name
  debug:
    var: socks_key_pair.key.name