---
- name: Launch instance
  amazon.aws.ec2_instance:
    aws_access_key: "{{ access_key }}"  # From vault as defined
    aws_secret_key: "{{ secret_key }}"
    key_name: "{{ socks_key_pair.key.name }}"
    security_group: "{{ sg_output.group_id }}"
    instance_type: "{{ instance_type }}"
    # instance_tags: "{{ my_tags|items2dict }}"
    image_id: "{{ ami_result.stdout }}"
    wait: true
    region: "{{ region }}"
    vpc_subnet_id: "{{ subnet_output.subnet.id }}"
    wait_timeout: 300
    network:
    assign_public_ip: true
    tags:
      name: "{{ tag_name }}"
    register: instance_output

- name: Print instance public ip address
  debug:
    var: instance_output.instances.public_ip_address

- name: Add new Instance to Host list
  add_host:
    hostname: "{{ instance_output.instances.public_ip_address }}"
    groupname: webserver

- name: Wait for SSH to Become available
  wait_for:
    host: "{{ instance_output.instances.public_ip_address }}"
    port: 22
    state: started
    timeout: 220