---
- name: Create security group
  ec2_security_group:
    name: sock_group
    description: Allow necessary traffic
    aws_access_key: "{{ access_key }}"  # From vault as defined
    aws_secret_key: "{{ secret_key }}"
    vpc_id: "{{ vpc_output.vpc.id }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
  register: sg_output

- name: Print security group id
  debug:
    var: sg_output.group_id