---
- name: create VPC
  amazon.aws.ec2_vpc_net:
    aws_access_key: "{{ access_key }}"  # From vault as defined
    aws_secret_key: "{{ secret_key }}"
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ region }}"
    state: present
  register: vpc_output

- name: Print id
  debug:
    var: vpc_output.vpc.id