---
- name: Subnet creation
  ec2_vpc_subnet:
    aws_access_key: "{{ access_key }}"  # From vault as defined
    aws_secret_key: "{{ secret_key }}"
    state: present
    vpc_id: "{{ vpc_output.vpc.id }}"
    cidr: "{{ subnet_cidr }}"
    region: "{{ region }}"
    tags:
      name: sock_subnet
  register: subnet_output

- name: Print Subnet id
  debug:
    var: subnet_output.subnet.id