---
- name: Gateway
  amazon.aws.ec2_vpc_igw:
    aws_access_key: "{{ access_key }}"  # From vault as defined
    aws_secret_key: "{{ secret_key }}"
    vpc_id: "{{ vpc_output.vpc.id }}"
    region: "{{ region }}"
    state: present
  register: igw_output

- name: Print id
  debug:
    var: igw_output.gateway_id